services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Only expose nginx to the outside world
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build: ./frontend
    # No direct port mapping needed for production
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=/api
    networks:
      - app-network

  backend:
    build: ./backend
    # No direct port mapping needed for production
    volumes:
      - ./backend:/app           # Mount backend code (for development)
      - ./config:/app/config:ro # <-- ADD THIS LINE (ro = read-only, recommended for config)
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/stellar_accord
      - SECRET_KEY=your_secret_key
      # Optional: You could explicitly set CONFIG_PATH if you don't want the default
      # - CONFIG_PATH=/app/config
    networks:
      - app-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stellar_accord
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: