# File Path: config/civilizations/thrizoth.yaml
# Purpose: Defines specific attributes for The Thrizoth civilization.

civilization:
  id: TH
  name: The Thrizoth
  # Formerly known as Arborealis Nexus

  homeworld_system_id: CD # System ID from config/sector_map.yaml
  homeworld_name_flavor: Verdant # Flavor name for their homeworld

  # List of Civilization IDs this civ cannot directly communicate with (GDD App B)
  communication_restrictions:
    - VN # Cannot communicate with Vasku

  # Resources where this civ has improved Kokoro mining yield (GDD App B / App F)
  # Format: ResourceID: bonus_percentage (as decimal)
  mining_specializations:
    RootMemoryStrands: 0.20 # +20% yield for Root Memory Strands
    MethasyntheticSpores: 0.20 # +20% yield for Methasynthetic Spores

  # Resources where this civ has reduced Kokoro mining yield (GDD App B / App F)
  # Format: ResourceID: penalty_percentage (as negative decimal)
  mining_inefficiencies:
    DuraniumAlloy: -0.15 # -15% yield for Duranium Alloy
    Neutronium: -0.15 # -15% yield for Neutronium


  # Initial Big Tech blueprint access is defined in config/technology/initial_blueprints.yaml
  # Initial resource inventory is defined in config/initial_state.yaml
